<div class="container" id="content">

<h1>About Krishna Engineering College</h1>
<br>
<p align="justify">
  Krishna Engineering College (KEC, Ghaziabad) was established in 2004 by Friends Charitable Society (FCS) Ghaziabad. FCS has eminent Businessmen, Industrialists and Professionals as its members. FCS members are also associated with other leading Educational Institutions in NCR and other region of UP like Krishna Institute of Engineering &amp; Technology (KIET), Inderprastha Engineering College (IPEC), and Krishna Dental College (KDC), Krishna Institute of Technology (KIOT), Krishna Girls Engineering College (KGEC), Krishna Institute of Management &amp; Technology (KIMT). KEC has been established as an institution for the millennium with a vision to turn out scholars who will be Global Players when they leave the portals of KEC. With this vision in the background, the college endeavours to impart core technical knowledge, help students develop requisite soft skills, instil an adaptability for change and builds cross cultural compatibility to its students. The college is approved by AICTE (Ministry of HRD, Government of India) and is affiliated to AKTU, Lucknow. Starting with four programmes in B.Tech.,the college currently offers six programmes in B.Tech.(Computer Science &amp; Engineering, Information Technology, Electronics &amp; Communication Engineering, Electrical &amp; Electronics Engineering, Mechanical Engineering and Civil Engineering) with an approved intake of 720 students/year. Within a span of 13 years, the college has established its credentials as an institution of repute by figuring among top 20 colleges of over 400 Engineering &amp; Technology Institutions of AKTU in session 2016-17. The college infrastructure is a planned endeavour built over a period with care and concern keeping all the needs of a premier Engineering Institution. The campus is located in Mohan Nagar, Ghaziabad, next to IAF Station Hindon and is strategically located vis-a-vis Delhi (5 Km from border), Ghaziabad (6 Km), 12 km from Noida and other areas like Vasundhara, Vaishali &amp; Kaushambi. The campus is spread over an area of 11 acres with plans for 3 academic blocks covering over 25000 Sq. meter of built up area, 3 Hostels (2 for boys and 1 for Girls) roughly with a capacity of 1000, an Auditorium, workshops, play grounds and quarters for the employees. Hello
</p>
<br>
<a href="../../static/pdf/about_institute/overview/KEC_Brochure_13_b1lIUPL_Isk23Ve.pdf" target="_blank"><h3>Click here to Download KEC Brochure</h3></a>
<br><br>

</div>